

import sbms

# get env object and clone it
Import('*')
env = env.Clone()

UTILITIES_LIBS = "UTILITIES"
env.AppendUnique(LIBS = UTILITIES_LIBS.split())

sbms.AddUtilities(env)
sbms.AddROOT(env)

sbms.executable(env)


