import os
import sbms

# get env object and clone it
Import('*')

env = env.Clone()

UTILITIES_LIBS = "UTILITIES"
env.AppendUnique(LIBS = UTILITIES_LIBS.split())
     
sbms.AddHDDM(env)
sbms.AddROOT(env)
sbms.AddUtilities(env)
   
sbms.executable(env)

