
import os
import sbms

# get env object and clone it
Import('*')

# Verify AMPTOOLS environment variable is set
if os.getenv('AMPTOOLS', 'nada')!='nada':

   env = env.Clone()
   
   AMPTOOLS_LIBS = "AMPTOOLS_AMPS AMPTOOLS_DATAIO AMPTOOLS_MCGEN UTILITIES"
   env.AppendUnique(LIBS = AMPTOOLS_LIBS.split())
   
   sbms.AddHDDM(env)
   sbms.AddROOT(env)
   sbms.AddAmpTools(env)
   sbms.AddUtilities(env)
   sbms.executable(env)

   print "COMPILEROLD =", env['CXX']
   env.Replace(CXX = 'mpicxx')
   print "COMPILERNEW =", env['CXX']

   env.Append(CXXFLAGS = '-DUSE_MPI')
   print "CXXFLAGS =", env['CXXFLAGS']
   if os.getenv('CUDA_INSTALL_PATH')!=None and os.path.exists('%s/lib/libAmpTools_GPU_MPI.a' % os.getenv('AMPTOOLS')):
      env.PrependUnique(LIBS = "AmpTools_GPU_MPI")
