#+title: The BGGEN simulation program
#+subtitle: Release {{{version}}}
#+author: Eugene Chudakov
#+STARTUP: showall
#+OPTIONS: ^:{}
#+OPTIONS: toc:4
# +STYLE: <link rel="stylesheet" type="text/css" href="style_3.css" />  

* Introduction
** This manual
This manual can be converted to html, providing hyperlinks, "rich text" etc:
#+begin_example
 $cd doc
 $emacs bggen-manual.org --batch -f org-export-as-html --kill # older org version <=7
 $emacs bggen-manual.org --batch -f org-html-export-to-html --kill # newer org version
#+end_example
 
** Purpose and functionality
BGGEN simulates photoproduction of hadronic events in a wide energy range. 
It can do two kinds of simulation:
1. Simulation of "minimum bias" events, matching the energy dependence of
    the total photoproduction cross section. It can be used for evaluation 
    of hadronic backgrounds for GlueX etc. There are two effective
    energy ranges:
   + for the beam energy E_{B}>3 GeV [[https://arxiv.org/abs/hep-ph/0603175][PYTHIA-6.4]] is used. 
   + for E_{B}<3 GeV a mixture of 10 dominant exclusive reactions is simulated.
     The cross section energy dependence and kinematic parameterization
      are taken from data. A sum of these reactions 
       nearly saturate the total cross section at the given energy.
   + switching between these two energy regimes is automatic and depends
     on the generated beam energy of the event 
2. Simulation of an exclusive binary reaction, say \gamma{}+p \rightarrow{} J/\psi{} + p
   according to the provided energy and /t/ dependence of the cross section. Decays
   of the produced particles are also simulated.
   Radiative corrections to decays can be simulated using the code /PHOTOS/
   ([[https://inspirehep.net/literature/756345][references therein]]).

The photon beam spectrum is calculated using the code from R.Jones for 
the coherent Bremsstrahlung.
The effective reaction rate for a given beam energy
is proportional to the product of the beam spectrum and the cross section of the reactions
simulated at the given energy. For simulation of "minimum bias events" the full photoproduction
cross section is used.

/BGGEN/ writes out the generated events in the HDDM format which can be used as input for 
the GlueX GEANT program.
 
The /PYTHIA/ event records are transferred to the output as they are. The "low-energy"
and binary reactions are simulated in the /BGGEN/ code, which includes simulating
of the initial kinematics and the particle's decays. 
 
** Major releases and updates

1. 2008 Jan: (E.Chudakov) 1-st release of /bggen/ for background (PYTHIA+low energy) simulation
2. 2012: Added functionality to simulate binary reactions (as J/\psi production). 
   For historic reasons this upgrade was forked into a clone of /bggen/, called /bggen_jpsi/.
3. 2017-2018: (R.Jones) Upgrade of the coherent radiation routine /cobrems.F/, in /bggen/.
   /bggen_jpsi/ was not upgraded.
4. 2019: (S.Dobbs) radiation in decays /PHOTOS/ was added to /bggen_jpsi/ (for J/\psi decays) 
5. 2022 Apr: (E.Chudakov) revision of the code, combining /bggen/ and /bggen_jpsi/ functionality
        in a single package, called at the moment /bggen_upd/, some functionality added, 
        and some changes to the interface are made.
   + Comparison of the results with the old code
     - PYTHIA: for identical initial parameters /bggen/ and /bggen_upd/ produced identical events
       (the first 1000 have been checked)
     - Low energy processes: also identical events with /bggen/
     - J/\psi production: because of a change in cobrems.F between /bggen_jpsi/ and /bggen/ (/bggen_upd/ uses
       the more recent version from /bggen/) the events were not identical. The distribution of the momenta
       of the final-state particles happen to be the same within the statistical fluctuations.
   + For the binary reaction 1 + 2 \rightarrow 3 + 4, we set 1: \gamma{} and 2: /proton/. The difference
     with /bggen_jpsi/:
     - The kinematic variable /t/ is defined now as (p_{3}-p_{1})^{2} (it was (p_{3}-p_{2})^{2}),
       Therefore, the particle order is now \gamma + p \rightarrow{} J/\psi + p. 
     - A cascade of decays of the particles 3 and 4  can be simulated.
     - The /t/ distribution can be set in a complex way - as a sum of two exponential functions, or/and a dipole
       function, set different in up to 5 beam energy regions.
   + For /PYTHIA/: an option for event selection is added. It allows to
     write out only the events with some combination of the produced particles, say events with \eta{}'.
   + The interface change:
     - Files /particle.dat/ and /pythia-geant.map/ are removed. The data are read in the /FFREAD/ format,
       from a separate file /particle.ffr/. The data can be redefined in the main /run.ffr/ - see the examples
       in the /run/ directory and explanations in this document.
     - New /FFREAD/ commands added allowing to print out lists of the particle names and features from /PYTHIA/  

** Installation

In order to compile the code one needs to copy the full GlueX software structure
(see [[https://halldweb.jlab.org/docs/build_scripts_web/][the manual]]). 
At JLab the easiest way is to use a computer that mounts =/group/halld=.
Let us say you have a directory =git=. I used the following:

#+begin_example
$ cd git/
$ git clone https://github.com/JeffersonLab/halld_sim
$ git clone https://github.com/JeffersonLab/build_scripts
$ source ./build_scripts/gluex_env_boot_jlab.sh
$ gxenv
$ cd halld_sim/halld_sim/src/programs/Simulation/bggen
$ scons -u install
#+end_example

This is the top structure:

#+begin_example
$ ls -l
drwxr-xr-x 3 gen halld-2 4096 Apr  7 22:24 code             # the main source code
drwxr-xr-x 2 gen halld-2 4096 Apr  8 00:16 doc              # documantation
-rwxr-xr-x 1 gen halld-2 4429 Mar 16 22:11 fix_warnings.py  # auxiliary for the PYTHIA code cleaning
-rw-r--r-- 1 gen halld-2   58 Mar 16 22:11 Makefile         #
drwxr-xr-x 2 gen halld-2 4096 Apr  4 19:54 paw              # for analysis of the ntuple output
-rw-r--r-- 1 gen halld-2 7922 Apr  1 14:13 README           #
drwxr-xr-x 2 gen halld-2 4096 Apr  7 21:58 run              # directory to run the program, contains input data
-rw-r--r-- 1 gen halld-2   77 Mar 16 22:11 SConscript       # 
drwxr-xr-x 2 gen halld-2 4096 Mar 16 22:11 xsec_table       # auxiliary for calculation \sigma(E) of J/psi 
#+end_example

* Input data and controls
** Input files
#+begin_example
lrwxrwxrwx 1 gen halld-2       12 Apr 13 11:14 fort.15 -> run_jpsi.ffr      # The symbolic links
lrwxrwxrwx 1 gen halld-2       12 Apr 12 14:25 fort.16 -> particle.ffr      # can be set to the files needed
lrwxrwxrwx 1 gen halld-2       17 Apr 12 17:02 fort.17 -> run_mcwrapper.ffr # for the current run
-rw-r--r-- 1 gen halld-2     3454 Apr 12 16:33 particle.ffr                 # table of particles and IDG --> KF matching
-rw-r--r-- 1 gen halld-2     1057 Mar 16 22:11 pythia.dat                   # input flags and values for /PYTHIA/
-rw-r--r-- 1 gen halld-2     8437 Apr 13 11:15 run_jpsi.ffr                 # example: control file for J/psi simulation
-rw-r--r-- 1 gen halld-2     3003 Apr 12 17:11 run_pyth.ffr                 # example: control file for BG simulation (/PYTHIA/ etc)
-rw-r--r-- 1 gen halld-2      426 Apr 12 17:01 run_mcwrapper.ffr            # auxiliary file with definitions to be changed by MCwrapper
#+end_example

The /*.ffr/ files are set in the [[http://cds.cern.ch/record/2296371/files/ffio.pdf][FFREAD]] format[fn:ffread].
[fn:ffread] /FFREAD/: The static variables are associated with text keys. The keys are set at 
the beginning of lines, followed by data (integer or real or character) in a flexible format.
The same key can be set multiple times in the input file, the data in the later line
overwrites the earlier lines. The keys started with * are treated differently - 
the data are treated once the key is read, and can be put into other locations. The next
similar key will not overwrite the previously set data. The lines are up to 120 characters long.
Comments can be put after the # sign. "C ..." in the first column is a comment line.

 
The main input file is read from /fort.15/.  It should be used for settings for a particular
computing job.
It is convenient to use a symbolic link 
to some particular file, say
#+begin_example
$ ln -s run_pyth.ffr fort.15
#+end_example
The other /FFREAD/ input files can be read out using an /FFREAD/ command /READ/ in /fort.15/.
They should be nearly static.
#+begin_example
LIST                    #    print the commands while reading
C ===    INPUT file for BGGEN
C
C ---      FFREAD format: 1) a command overwrites the same command above in the file; 
C                         2) the KEYS should start from the column 1; lines are up to 120 characters
C                         3) format is flexible, can mix reals and integers; I suggest to use the right type (not 4 for 4.0)
C                         4) one can fill an array from any position, the rest is not changed, 
C                                    say "SELECTEV 2=111 -211" fills the positions 2 and 3
C                         5) # - the rest of the line is ignored   
C
READ     16             # read the file with particle definitions 
C
C ------------- General controls ---------------
SIMUL     0             # type of simulation =0 - BG, =1 - exclusive (J/psi ...)         
C                        =0 - BG (PYTHIA+low energy reactions)              
#+end_example
A note: the commands lower in a /FFREAD/ input file can changed the data set by commands upper in the file. 

The flag /SIMUL=0/ is set for the background simulation - /PYTHIA/+"low energy"

*** Particle lists and interface to /GEANT/
/BGGEN/ prepares data (event records) for /GEANT/ and uses internally the /GEANT3/ particle /IDG-s/, 
say /IDG=14/ for protons. At the /BGGEN/ output there are two types of particles:
+ Particles decayed in /PYTHIA/ or /BGGEN/. For them /BGGEN/ sets /IDG=0/ for the output. They are not 
  processed by /GEANT/
+ Particles to be tracked in /GEANT/, which includes possible decays set in /GEANT/ (several decay modes
  may be included).  
  They are identified by the proper /IDG/. These should include:
  - particles leaving signals in the detectors
  - particles with a considerable decay path, as \Lambda{}^{0}
  - short living particles not specified in the standard /GEANT/, for example \eta{}' was not set in /GEANT3/. 
/PYTHIA/ is using a standard particle nomenclature (see a PDG book for explanations), 
In /PYTHIA/ for this particle /ID/ a variable name /KF/ is typically used. For the particles not decayed
(or not otherwise vanished) in /PYTHIA/ a match between /KF/ and /IDG/ must be set.

/GEANT3/ sets up to 50 particles in the code with IDG from 1 to 50. The list does not contain
low resonances as \rho and \Delta. The particle properties for /BGGEN/ are set in the file /particle.ffr/.
Many of these definitions are needed for the proper operation of /BGGEN/, one
should leave the /IDG \rightarrow KF/ relations, and the masses as they are. 
#+begin_example
$cat particle.ffr
C   PYTHIA: PY_dec=0 turns off decays of this particle in PYTHIA (left to GEANT tracking)
C   Exclusive production (SIMUL>0): decay_prod and decay_angle are used
C   column# 1        2    3     4        5        6   7   8     9    10
C          IDG     KF  PY_dec  mass    width     decay_prod decay_angle
*PARTICLE   1       22    0    0.0       0.       0   0   0     0   'gamma'
*PARTICLE   2      -11    0    0.000511  0.       0   0   0     0   'e+'
*PARTICLE   3       11    0    0.000511  0.       0   0   0     0   'e-'
*PARTICLE   4       12    0    0.0       0.       0   0   0     0   'neutrino'
*PARTICLE   5      -13    0    0.10566   0.       0   0   0     0   'mu+'
*PARTICLE   6       13    0    0.10566   0.       0   0   0     0   'mu-'
*PARTICLE   7      111    0    0.13498   0.       0   0   0     0   'pi0'
*PARTICLE   8      211    0    0.13957   0.       0   0   0     0   'pi+'
*PARTICLE   9     -211    0    0.13957   0.       0   0   0     0   'pi-'
*PARTICLE  10      130    0    0.49761   0.       0   0   0     0   'K0_L'
*PARTICLE  11      321    0    0.49368   0.       0   0   0     0   'K+'
*PARTICLE  12     -321    0    0.49368   0.       0   0   0     0   'K-'
*PARTICLE  13     2112    0    0.93956   0.       0   0   0     0   'neutron'
*PARTICLE  14     2212    0    0.93827   0.       0   0   0     0   'proton'
*PARTICLE  15    -2212    0    0.93827   0.       0   0   0     0   'antiproton'
*PARTICLE  16      310    0    0.49761   0.       0   0   0     0   'K0_S'
*PARTICLE  17      221    0    0.54786   0.       0   0   0     0   'eta'
*PARTICLE  18     3122    0    1.11568   0.       0   0   0     0   'Lambda'
*PARTICLE  19     3222    0    1.18937   0.       0   0   0     0   'Sigma+'
*PARTICLE  20     3212    0    1.19264   0.       0   0   0     0   'Sigma0'
*PARTICLE  21     3112    0    1.18937   0.       0   0   0     0   'Sigma+'
*PARTICLE  22     3322    0    1.31486   0.       0   0   0     0   'Xi0'
*PARTICLE  23     3312    0    1.32171   0.       0   0   0     0   'Xi-'
*PARTICLE  24     3334    0    2.252     0.       0   0   0     0   'Omega-'
*PARTICLE  25    -2112    0    0.93956   0.       0   0   0     0   'antineutron'
*PARTICLE  26    -3122    0    1.11568   0.       0   0   0     0   'antiLambda'
*PARTICLE  27    -3112    0    1.18937   0.       0   0   0     0   'antiSigma-'
*PARTICLE  28    -3212    0    1.19264   0.       0   0   0     0   'antiSigma0'
*PARTICLE  29    -3222    0    1.18937   0.       0   0   0     0   'antiSigma-'
*PARTICLE  30    -3322    0    1.31486   0.       0   0   0     0   'antiXi0'
*PARTICLE  31    -3312    0    1.32171   0.       0   0   0     0   'antiXi+'
*PARTICLE  32    -3334    0    2.252     0.       0   0   0     0   'antiOmega+'
*PARTICLE  33      -15    0    1.7768    0.       0   0   0     0   'tau+' 
*PARTICLE  34       15    0    1.7768    0.       0   0   0     0   'tau-' 
*PARTICLE  35      411    0    1.8696    0.       0   0   0     0   'D+' 
*PARTICLE  36     -411    0    1.8696    0.       0   0   0     0   'D-' 
*PARTICLE  37      421    0    1.8648    0.       0   0   0     0   'D0' 
*PARTICLE  38     -421    0    1.8648    0.       0   0   0     0   'anti D0' 
*PARTICLE  39      431    0    1.9685    0.       0   0   0     0   'Ds+' 
*PARTICLE  40     -431    0    1.9685    0.       0   0   0     0   'Ds-' 
*PARTICLE  41     4122    0    2.2851    0.       0   0   0     0   'Lambda_c+' 
*PARTICLE 121      331    1    0.95778   0.       0   0   0     0   'etaprime'
*PARTICLE 122      223    1    0.78265   0.0085   9   8   7     0   'omega'
*PARTICLE 123      213    1    0.77526   0.149    8   7   0     1   'rho+'
*PARTICLE 124      113    1    0.77526   0.149    9   8   0     1   'rho0'
*PARTICLE 125     -213    1    0.77526   0.149    9   7   0     1   'rho-'
*PARTICLE 126      333    1    1.0194    0.      11  12   0     0   'phi'
*PARTICLE 127     2224    1    1.232     0.118   14   8   0     0   'Delta++'
*PARTICLE 128     2214    1    1.232     0.118   14   7   0     0   'Delta+'
*PARTICLE 129     2114    1    1.232     0.118   14   9   0     0   'Delta0'
*PARTICLE 130     1114    1    1.232     0.118   13   9   0     0   'Delta-'
END
#+end_example
The purpose of the flags are:
+ The flag in column 3 /PY_dec=0/ forbids the decays of this particle in /PYTHIA/ (the are left to /GEANT/).
+ /BGGEN/ simulates decays for the "low - energy" and for binary reactions The decay flags in the columns 6-8
  are the /IDGs/ for the decay products (up to 3). Only one decay mode is used. The flag in the column 9:
  - =0 - isotropic decays
  - =1 - \rho - type angular distribution
  - =2 - J/\psi - type angular distribution

In the main input file one can redefine the decay parameters or add new particles, for example:

#+begin_example 
*PARTICLE  17      221    0    0.54786   0.       8   9   7     0   'eta'  # eta will decay in bggen and not send to GEANT
*PARTICLE 183      443    1    3.0969    0.       2   3   0     2   'J/psi'
#+end_example

After initialization /BGGEN/ prints a table of the locally defined particles:
#+begin_example 
 ================================================================================
 Particle list locally defined   ID_GEant<33 are also defined in the GEANT3 code
 ID_Geant KF PY_dec N_dec  ID_decays dec_flg     mass     width     name
   1      22     0    0     0   0   0    0     0.000000   0.0000     gamma           
   2     -11     0    0     0   0   0    0     0.000511   0.0000     e+              
   3      11     0    0     0   0   0    0     0.000511   0.0000     e-              
   4      12     0    0     0   0   0    0     0.000000   0.0000     neutrino        
   5     -13     0    0     0   0   0    0     0.105660   0.0000     mu+             
   6      13     0    0     0   0   0    0     0.105660   0.0000     mu-             
   7     111     0    0     0   0   0    0     0.134980   0.0000     pi0             
   8     211     0    0     0   0   0    0     0.139570   0.0000     pi+             
   9    -211     0    0     0   0   0    0     0.139570   0.0000     pi-             
  10     130     0    0     0   0   0    0     0.497610   0.0000     K0_L            
  11     321     0    0     0   0   0    0     0.493680   0.0000     K+              
  12    -321     0    0     0   0   0    0     0.493680   0.0000     K-              
  13    2112     0    0     0   0   0    0     0.939560   0.0000     neutron         
  14    2212     0    0     0   0   0    0     0.938270   0.0000     proton          
  15   -2212     0    0     0   0   0    0     0.938270   0.0000     antiproton      
  16     310     0    0     0   0   0    0     0.497610   0.0000     K0_S            
  17     221     0    0     0   0   0    0     0.547860   0.0000     eta             
  18    3122     0    0     0   0   0    0     1.115680   0.0000     Lambda          
  19    3222     0    0     0   0   0    0     1.189370   0.0000     Sigma+          
  20    3212     0    0     0   0   0    0     1.192640   0.0000     Sigma0          
  21    3112     0    0     0   0   0    0     1.189370   0.0000     Sigma+          
  22    3322     0    0     0   0   0    0     1.314860   0.0000     Xi0             
  23    3312     0    0     0   0   0    0     1.321710   0.0000     Xi-             
  24    3334     0    0     0   0   0    0     2.252000   0.0000     Omega-          
  25   -2112     0    0     0   0   0    0     0.939560   0.0000     antineutron     
  26   -3122     0    0     0   0   0    0     1.115680   0.0000     antiLambda      
  27   -3112     0    0     0   0   0    0     1.189370   0.0000     antiSigma-      
  28   -3212     0    0     0   0   0    0     1.192640   0.0000     antiSigma0      
  29   -3222     0    0     0   0   0    0     1.189370   0.0000     antiSigma-      
  30   -3322     0    0     0   0   0    0     1.314860   0.0000     antiXi0         
  31   -3312     0    0     0   0   0    0     1.321710   0.0000     antiXi+         
  32   -3334     0    0     0   0   0    0     2.252000   0.0000     antiOmega+      
 121     331     1    0     0   0   0    0     0.957780   0.0000     etaprime        
 122     223     1    3     9   8   7    0     0.782650   0.0085     omega           
 123     213     1    2     8   7   0    1     0.775260   0.1490     rho+            
 124     113     1    2     9   8   0    1     0.775260   0.1490     rho0            
 125    -213     1    2     9   7   0    1     0.775260   0.1490     rho-            
 126     333     1    2    11  12   0    0     1.019400   0.0000     phi             
 127    2224     1    2    14   8   0    0     1.232000   0.1180     Delta++         
 128    2214     1    2    14   7   0    0     1.232000   0.1180     Delta+          
 129    2114     1    2    14   9   0    0     1.232000   0.1180     Delta0          
 130    1114     1    2    13   9   0    0     1.232000   0.1180     Delta-          
 183     443     1    2     2   3   0    2     3.096900   0.0000     J/psi           
#+end_example

*** Input for /PYTHIA/

/PYTHIA/, including /PITHIA-6.4/ was tuned for much higher energies,
We are using a version tuned for the experiment HERMES. HERMES used
\approx 30 GeV electrons, which was considered a low energy for
/PYTHIA/.  They made a few small changes in the code and tuned the
input parameters. We are using their settings stored in the file
/pythia.dat/. Similar commands to /PYTHIA/ can be specified
in the /FFREAD/ format. They are processed after the commands
in /pythia.dat/. The later commands can redefine the previous ones. 
Also, a few commands to /PYTHIA/ are done in the
/bggen/ code, for the beam and target configuration.  At the
initialization /PYTHIA/ prints the changes of the parameters with
respect to defauls:
#+begin_example
     MDCY(102,1)    changed from              1 to              0 no decay of pi0
     MDCY(112,1)    changed from              1 to              0 no decay of Ks_0
     MDCY(109,1)    changed from              1 to              0 no decay of eta
     MDCY(164,1)    changed from              1 to              0 no decay of Lambda_0
     MDCY(169,1)    changed from              1 to              0 no decay of Sigma+
     MDCY(167,1)    changed from              1 to              0 no decay of Sigma0
     MDCY(162,1)    changed from              1 to              0 no decay of Sigma-
     MDCY(174,1)    changed from              1 to              0 no decay of Xi0
     MDCY(172,1)    changed from              1 to              0 no decay of Xi-
     MDCY(176,1)    changed from              1 to              0 no decay of Omega-
     MDCY(15,1)     changed from              1 to              0 no decay of tau
     MDCY(122,1)    changed from              1 to              0 no decay of D+ 
     MDCY(125,1)    changed from              1 to              0 no decay of D0 
     MDCY(128,1)    changed from              1 to              0 no decay of Ds 
     MDCY(181,1)    changed from              1 to              0 no decay of Lambda_c
     msel           changed from              1 to              2 more processes with photon included
     MSTP(13)       changed from              1 to              2 Q2 range defined by PARP(13) - appropriate for photoproduction
     MSTP(20)       changed from              3 to              0 no VMD suppression 
     MSTP(58)       changed from              5 to              4 max number of quark flavors
     MSTP(92)       changed from              3 to              4 a function for splitting into 2 jets
     MSTP(101)      changed from              3 to              1 diffractive system parameter
     MSTP(121)      changed from              0 to              1 wider range of diff. cross sections
     PARP(2)        changed from       10.00000 to        2.54739 the lowest CM energy : Egamma(Lab)=3 GeV
     PARP(18)       changed from        0.40000 to        0.17000 parameter of GVMD with repect to VMD
     PARP(91)       changed from        1.00000 to        0.40000 parameter for beam-remnant treatment
     PARP(93)       changed from        5.00000 to        2.00000 similar to (91)
     PARP(99)       changed from        1.00000 to        0.40000 similar to (91)
     PARP(102)      changed from        0.28000 to        0.50000 min mass of excitatation, in VMD gamma goes to masses of rho etc
     PARP(103)      changed from        1.00000 to        0.50000 similar
     PARP(104)      changed from        0.80000 to        0.30000 min energy above thresholds for some reactions
     PARP(111)      changed from        2.00000 to        0.00000 min invzriant mass of the remnant hadronic system
     PARP(121)      changed from        1.00000 to        2.00000 a factor for the max cross section: see MSTP(121)
     PARP(161)      changed from        2.20000 to        3.00000 coupling of photon to rho 
     PARP(162)      changed from       23.60000 to       24.60000 coupling of photon to omega
     PARP(165)      changed from        0.50000 to        0.47679 a factor taking into account longit. photons
     PARP(166)      changed from        0.00000 to        0.67597 a parameter for rho production obtained by HERMES
     PARJ(1)        changed from        0.10000 to        0.02900 suppression of diquark-antidiq pair compared to q-antiq 
     PARJ(2)        changed from        0.30000 to        0.28300 suppression of s-sbar to u-ubar
     PARJ(3)        changed from        0.40000 to        1.20000 suppression (P(us)Pud))/(P(s)/Pd))
     PARJ(21)       changed from        0.36000 to        0.40000 transv momentum distrib. of primary hadrons 
     PARJ(23)       changed from        0.01000 to        0.03000 also about transv. distributions
     PARJ(41)       changed from        0.30000 to        1.94000 parameters of LUND fragment. function
     PARJ(42)       changed from        0.58000 to        0.54400 parameters of LUND fragment. function
     PARJ(45)       changed from        0.50000 to        1.05000 parameters of LUND fragment. function
     MSTJ(12)       changed from              2 to              1 diquark-antidiq pairs allowed, diquark treated as a unit
     MSTJ(45)       changed from              5 to              4 max flavor in gluon->q qbar
     MSTU(112)      changed from              5 to              4 number of flavor in alpha_s expression
     MSTU(113)      changed from              3 to              4 min number of flavor in alpha_s expres
     MSTU(114)      changed from              5 to              4 max number of flavors in alpha_s expr.
     CKIN(1)        changed from        2.00000 to        1.00000 min sqrt(s)
     CKIN(66)       changed from       -1.00000 to      100.00000 max space-like virtuality Q^2 of photons (-1 - no upper limit)
     MSTP(171)      changed from              0 to              1 variable beam energy
     MSTP(172)      changed from              2 to              1 possible configurations tried until one is accepted
     PARP(2)        changed from        2.54739 to        2.42000 min sqrt(s) with a 5% margin from the 3 GeV beam limit 
#+end_example
An example of commands that can be used in /fort.15/ (up to 500 such lines):
#+begin_example
*PYTMOD 'PARP(103)=0.45'   # min mass of excitation
*PYTMOD 'PARP(104)=0.25'   # min energy above threshold
#+end_example


** Main input file /fort.15/ for setting parameters and controls 
The commands can be grouped into several sections:
*** general controls
Note: some commands are commented out by a leading "C " in these examples.
#+begin_example
C ------------- General controls ---------------
SIMUL     0             # type of simulation =0 - BG, =1 - binary, exclusive reactions
C                        =0 - BG (PYTHIA+low energy reactions) 
C                        =1 - exclusive binary photoproduction, for example gamma+p-->J/psi+p        
TRIG     1000000        # number of events to simulate
NPRIEV       100        # number of events to print (after selection, see SELECTEV) 
RNDMSEQ     0           # random number sequence     integer values
RUNNO       2           # specify run number
C                       
C -- writing out events
C        HDDM  simple  ntuple
WROUT      1      0     0   
...........
...........
C
READ 17                 # read variables for MCWrapper
C
KEYS                    # print all the FF keys
STOP
#+end_example

*** beam definitions
#+begin_example
C ------------  Beam ---------------------------
EELEC         11.7      # electron beam energy
EEMIT          1.E-8    # beam emittance rad m
EPHLIM   0.15 11.7      # photon beam energy range in GeV
EPHLIM    6.0 11.7      # photon beam energy range in GeV 
EPEAK          8.7      # coherent peak energy
ZCOLLIM     7600.       # distance to the collimator in cm
DCOLLIM        0.005    # collimator diameter in m
RADTHICK      50.E-6    # thickness of the radiator in m 
C ----------------------------------------------
C
PARTINIT  1  14         # GEANT types of the interacting particles: gamma proton
C
#+end_example
*** Setting for the minimum bias events simulation: PYTHIA+low energy
#+begin_example 
 ------------  BG simulation ------------------
C                       PYTHIA flags are set in a file pythia.dat
EPYTHMIN     3.         # minimal energy for PYTHIA simulation
ELOWMIN      0.15       # minimal energy for the low energy processes generator 
C
C LISTPYTH    2           # >0 print the PYTHIA particle list at the initialization stage:
C                         =1 without decays
C                         =2 with decays of the particles, allowed to decay in PYTHIA 
C LISTMLIM    6.          #  amlim print only particles with mass<amlim
C
C ------------- Event selection ----------------
C
C SELECTEV    333         # select events with at least one phi (KF codes used), array(5)
C                         # SELECTEV 333 221   # would require at least one \phi AND one \eta (up to 5 particles)
#+end_example

*** Setting for the binary reaction simulation: here for J/\psi p 

#+begin_example
C ==========================================================================
C  reac - J/psi: gamma p -> J/psi p 
C
*PARTICLE 183      443    1    3.0969    0.       2   3   0     2   'J/psi'
C
REACPART  183 14      # reaction final state j/psi and proton  
RADCORR   183         # radiative corrections for J/psi decay           
C
C ----------------------------------------------------
C               t-dependence 3 energy intervals  (Lubomir)
C         tmin tmax
REACTLIM  -11.   0.          # t limits (simulated in narrower ranges depending on the beam energy)
C                a1      a2     a3    a4    a5      - parameters of the t-distribution function 
C          Emax  Norm  slope1 slope2 fac2   fac3   : dsigma/dt~ Norm*(exp(slope1*t)+exp(slope2*t)*fac2)/(1-fac3**t)^4
REACTDIS1  9.28  1.    1.52  -0.650 0.00119  0.  # energy range 1       Ebeam<9.28 GeV
REACTDIS2 10.36  1.    1.22   0.268 0.033    0.  # energy range 2  9.28<Ebeam<10.36 GeV
REACTDIS3 13.    1.    1.89   0.646 0.149    0.  # energy range 3 10.36<Ebeam<13 GeV
C  5 ranges can be used
C REACTDIS5 ...
C REACTDIS1  13.    1.    1.16     0.  0.0    0.   # example for a single exponential exp(1.16*t)
C ----------------------------------------------------
C
C          Energy dependence of the cross section, nb
C          Emin     Emax    N points (up to 3000 points)
REACENER  8.2300   13.0000  500 
 0.0508535 0.0610938 0.0699333 0.0778633 0.0851418 0.0919165 0.0983004 0.104362 0.110155 0.115718
 0.121088 0.126288 0.131342 0.136269 0.141074 0.145773 0.150385 0.154911 0.159358 0.163734
 0.168049 0.172301 0.176504 0.18066 0.184763 0.188831 0.192858 0.196854 0.200811 0.204744
 0.208645 0.212519 0.216372 0.220206 0.224011 0.227806 0.23158 0.235336 0.239082 0.242808
 0.246524 0.250228 0.253924 0.257614 0.26129 0.264963 0.268626 0.272283 0.275937 0.279586
 0.283225 0.286867 0.290506 0.294142 0.297774 0.301412 0.305043 0.308676 0.312307 0.315941
 0.319574 0.323215 0.326852 0.330493 0.334142 0.33779 0.341442 0.345096 0.348755 0.352414
 0.356085 0.359756 0.363435 0.367123 0.370814 0.374512 0.378211 0.381919 0.385638 0.389355
 0.393086 0.396825 0.400565 0.40432 0.408083 0.411851 0.415624 0.419412 0.423203 0.427004
 0.430815 0.434633 0.438465 0.442303 0.446153 0.450006 0.453878 0.457751 0.461639 0.465531
 0.469444 0.473358 0.477284 0.481226 0.485173 0.489134 0.493101 0.497079 0.501073 0.505075
 0.509087 0.513113 0.517152 0.521195 0.525249 0.529327 0.533407 0.537495 0.541598 0.545719
 0.549844 0.553983 0.558134 0.5623 0.566477 0.570663 0.574862 0.579069 0.583295 0.587526
 0.591776 0.596041 0.600311 0.604591 0.608888 0.613199 0.617519 0.621853 0.626199 0.630559
 0.634929 0.639313 0.643712 0.648117 0.652539 0.656976 0.661417 0.665877 0.670351 0.674834
 0.679334 0.683847 0.688364 0.6929 0.69745 0.702007 0.706581 0.71117 0.715765 0.72038
 0.724999 0.729644 0.734291 0.738954 0.743632 0.748314 0.753016 0.757737 0.762456 0.767189
 0.771948 0.776709 0.781491 0.78628 0.791085 0.795892 0.800727 0.805566 0.810418 0.815289
 0.820164 0.825056 0.829963 0.834878 0.83981 0.844749 0.849707 0.85467 0.85965 0.864647
 0.869645 0.874662 0.879696 0.88474 0.889792 0.894861 0.899935 0.90503 0.910137 0.915257
 0.920382 0.925523 0.930677 0.935836 0.941017 0.946205 0.951407 0.95662 0.961849 0.967088
 0.97234 0.977606 0.982881 0.988163 0.993466 0.998779 1.0041 1.00943 1.01478 1.02014
 1.02551 1.03089 1.03629 1.04169 1.04711 1.05254 1.05797 1.06343 1.06888 1.07437
 1.07985 1.08535 1.09086 1.09638 1.10191 1.10745 1.113 1.11858 1.12415 1.12974
 1.13534 1.14095 1.14657 1.15221 1.15785 1.16351 1.16918 1.17485 1.18054 1.18624
 1.19196 1.19767 1.20341 1.20915 1.21489 1.22066 1.22643 1.23222 1.23801 1.24382
 1.24964 1.25546 1.2613 1.26715 1.273 1.27888 1.28475 1.29064 1.29654 1.30245
 1.30837 1.3143 1.32024 1.32618 1.33215 1.33812 1.34409 1.35008 1.35609 1.36209
 1.36811 1.37413 1.38017 1.38621 1.39227 1.39834 1.40442 1.4105 1.4166 1.4227
 1.42881 1.43493 1.44106 1.4472 1.45335 1.45951 1.46568 1.47186 1.47805 1.48424
 1.49045 1.49667 1.50287 1.50911 1.51535 1.5216 1.52786 1.53412 1.54041 1.54669
 1.55297 1.55927 1.56558 1.57189 1.57821 1.58455 1.59091 1.59726 1.60361 1.60998
 1.61635 1.62274 1.62913 1.63553 1.64194 1.64835 1.65477 1.6612 1.66764 1.67409
 1.68054 1.687 1.69347 1.69994 1.70643 1.71292 1.71943 1.72594 1.73245 1.73898
 1.74551 1.75204 1.75859 1.76513 1.77169 1.77826 1.78484 1.79142 1.79801 1.8046
 1.8112 1.8178 1.82443 1.83105 1.83767 1.84432 1.85095 1.85761 1.86427 1.87093
 1.87759 1.88427 1.89095 1.89763 1.90434 1.91104 1.91774 1.92446 1.93118 1.93791
 1.94463 1.95138 1.95813 1.96488 1.97164 1.9784 1.98517 1.99195 1.99874 2.00552
 2.01231 2.01911 2.02592 2.03272 2.03955 2.04637 2.05319 2.06004 2.06686 2.07372
 2.08057 2.08743 2.09429 2.10115 2.10803 2.1149 2.12179 2.12868 2.13557 2.14247
 2.14936 2.15627 2.16319 2.17012 2.17703 2.18396 2.1909 2.19784 2.20477 2.21173
 2.21869 2.22563 2.23261 2.23957 2.24654 2.25353 2.26051 2.26749 2.27448 2.28147
 2.28847 2.29547 2.30249 2.30949 2.31652 2.32353 2.33056 2.33759 2.34463 2.35165
 2.35871 2.36575 2.3728 2.37986 2.38691 2.39398 2.40105 2.40811 2.4152 2.42227
 2.42934 2.43642 2.44352 2.45062 2.45771 2.46481 2.47191 2.47903 2.48614 2.49325
 2.50037 2.50749 2.51462 2.52176 2.52888 2.53602 2.54316 2.55031 2.55745 2.56458
 2.57174 2.5789 2.58605 2.59323 2.60038 2.60755 2.61472 2.6219 2.62907 2.63625
 2.64343 2.65061 2.65782 2.66499 2.67218 2.67937 2.68658 2.6938 2.701 2.7082
 2.7154 2.72262 2.72983 2.73706 2.74427 2.75151 2.75873 2.76595 2.77318 2.78043
 2.78765 2.7949 2.80213 2.80937 2.81661 2.82385 2.83112 2.83836 2.84561 2.85287
#+end_example

The beam energy dependence is defined as a table. The /t/-dependence can be set
in up to 5 beam energy intervals as a function of five parameters /a_{1} - a_{5}/:

/d\sigma{}/dt ~ a_{1}(e^{a_{2}t}+e^{a_{3}t}a_{4})/(1-a_{5}t)^{4}/

it is a sum of two exponential functions times the dipole function from M.Strikman et al. 
By the choice of
the parameters one can set functions from a single exponential, to a double
exponential, a pure dipole, or any combination. Note that /t/ is negative.
One can set different function in up to 5 beam energy intervals. In the example above 
3 intervals are set.
 For each interval (commands REACTDIS1, REACTDIS2, .. REACTDIS5) the first variable 
specified the maximum energy /E_{max}/. In order to select the right interval for the given
event the beam energy is compared with this limits sequentially. A command:
#+begin_example 
REACTDIS1  13.    1.    1.16     0.  0.0    0.   # example for a single exponential exp(1.16*t)
#+end_example
would set only one energy interval (since /E_{beam}<13 GeV/) and a single exponential 
function with a slope of 1.16 /GeV^{-1}/.

A command
#+begin_example 
REACTLIM  -11.   0.          # t limits (simulated in narrower ranges depending on the beam energy)
#+end_example
sets a range of the /t/ variable wide enough for all beam energies. 
Simulation is done in the proper interval for the given beam energy in the event.

*** List of all keys

#+begin_example 
|-----------+------------------+------------+---------+------------------+--------------------------------------------------------------|
| Key       | Variable to fill | # of words | Type    |          Default | Function                                                     |
|-----------+------------------+------------+---------+------------------+--------------------------------------------------------------|
| DCOLLIM   | DCOLL            |          1 | REAL    |           0.0050 | Diameter of the collimator, m                                |
| EELEC     | EELEC            |          1 | REAL    |              12. | Electron beam energy, GeV                                    |
| EEMIT     | EEMIT            |          1 | REAL    |            1.E-8 | Beam emittance r * m                                         |
| ELOWMIN   | ELOWMIN          |          1 | REAL    |             0.15 | Minimal beam energy for low energy background generator, GeV |
| EPEAK     | EPEAK            |          1 | REAL    |               9. | The edge of the coherent peak, GeV                           |
| EPHLIM    | EPH_LIM(1)       |          2 | REAL    |         0.15 12. | Photon beam energy range, GeV                                |
| EPYTHMIN  | EPYMIN           |          1 | REAL    |               3. | Minimal beam energy for PYTHIA                               |
| LISTPYTH  | LISTPYTH         |          1 | INTEGER |                0 | =1 print PYTHIA particle list, =2 + decay channels           |
| LISTMLIM  | AMLIST           |          1 | REAL    |               6. | Print particles info if mass<AMLIST                          |
| NPRIEV    | NPRIEV           |          1 | INTEGER |                0 | Number of events to print                                    |
| *PARTICLE | K_PTMP(1)        |         16 | MIXED   |             16*0 | Particles parameters, used as *PARTICLE                      |
| PARTINIT  | IPINIT(1)        |          2 | INTEGER |            1  14 | Geant particle IDs for the beam and target                   |
| *PYTMOD   | KPYMOD(1)        |          8 | MIXED   |           8*' '  | Commands to PYTHIA, as *PYTMOD 'PARP(2)=3.'                  |
| RADCORR   | IRADCORR(1)      |         10 | INTEGER |                0 | Do rad corrections for decays of particles with KF listed    |
| RADTHICK  | RADT             |          1 | REAL    |           50.E-6 | Radiator thickness in m                                      |
| REACENER  | ELREAC(1)        |       3003 | MIXED   | -1. -1. 0 3000*0 | Binary reaction energy dependence: range, N points, xsection |
| REACPART  | IPREAC(1)        |          2 | INTEGER |           -1  -1 | Geant particle IDs for the exclusive binary reaction         |
| REACTDIS1 | TPAREAC(1,1)     |         11 | REAL    |            11*0. | /t/ distr: E_{max}, parameters of the function               |
| REACTDIS2 | TPAREAC(1,2)     |         11 | REAL    |            11*0. | ... same                                                     |
| REACTDIS3 | TPAREAC(1,3)     |         11 | REAL    |            11*0. | ... same                                                     |
| REACTDIS4 | TPAREAC(1,4)     |         11 | REAL    |            11*0. | ... same                                                     |
| REACTDIS5 | TPAREAC(1,5)     |         11 | REAL    |            11*0. | ... same                                                     |
| REACTLIM  | TLREAC(1)        |          2 | REAL    |           0.  0. | /t/ range                                                    |
| RNDMSEQ   | IRND_SEQ         |          1 | INTEGER |                0 | Random number seed (RLUX generator), any integer number      |
| RUNNO     | RUNNO            |          1 | INTEGER |                2 | Run number - arbitrary                                       |
| SELECTEV  | KFEVSEL(1)       |          5 | INTEGER |              5*0 | Select events with all non zero KF1 .. KF5 particles         |
| SIMUL     | ISIMUL           |          1 | INTEGER |                0 | \=0 - /PYTHIA/ + low energy; =1 - binary reaction            |
| TRIG      | NEVENT           |          1 | INTEGER |                0 | Number of events to simulate                                 |
| VERTEX    | VERTEX(1)        |          3 | REAL    |             3*0. | Vertex position (not used)                                   |
| WROUT     | IWROUT(1)        |          3 | INTEGER |          1  0  0 | >0 Write events to HDDM, simple, paw ntuple formats          |
| ZCOLLIM   | ZCOLL            |          1 | REAL    |            7600. | Distance between the radiator and the collimator, cm         |
|-----------+------------------+------------+---------+------------------+--------------------------------------------------------------|
#+end_example

* Physics processes
** /PYTHIA/ results
   /PYTHIA/ hadroproduction model has been tuned to high, and recently
   to very high energies. One should not expect it to give a very
   realistic production ratio of various final states, and of their
   kinematic distribution. There are other limitation:
+ Only the lowest light-quark resonances are included
+ No polarization effects are considered.

At the end of the job /BGGEN/ prints the statistics of the particles produced
by /PYTHIA/. Here is an example of such a record for 100M simulated events
in an energy range 6 - 11.7 GeV.
#+begin_example  
 PYTHIA total multiplicity in simulated events
      multiplicity          kf   %undecayed   kc   mass    name 
         79895105            1      0.000      1   0.3300  d               
         42951710           -1      0.000      1   0.3300  dbar            
        113196384            2      0.000      2   0.3300  u               
         44670384           -2      0.000      2   0.3300  ubar            
          8355361            3      0.000      3   0.5000  s               
          7150101           -3      0.000      3   0.5000  sbar            
             2278            4      0.000      4   1.5000  c               
             1884           -4      0.000      4   1.5000  cbar            
             3837           11    100.000     11   0.0005  e-              
             3837          -11    100.000     11   0.0005  e+              
             2059           13    100.000     13   0.1057  mu-             
             2059          -13    100.000     13   0.1057  mu+             
         29397163           21      0.000     21   0.0000  g               
          3364579           22    100.000     22   0.0000  gamma           
         96940280           91      0.000     91   0.0000  cluster         
         72013029           92      0.000     92   0.0000  string          
        126679960          111    100.000    102   0.1350  pi0             
         35402098          113      0.000    103   0.7685  rho0            
          8138760          130    100.000    105   0.4977  K_L0            
        151821892          211    100.000    106   0.1396  pi+             
        121765772         -211    100.000    106   0.1396  pi-             
         23014067          213      0.000    107   0.7669  rho+            
         19300831         -213      0.000    107   0.7669  rho-            
         17956151          221    100.000    109   0.5475  eta             
         22801094          223      0.000    110   0.7819  omega           
          8143989          310    100.000    112   0.4977  K_S0            
          9203506          311      0.000    113   0.4977  K0              
          6270425         -311      0.000    113   0.4977  Kbar0           
          3907463          313      0.000    114   0.8961  K*0             
          2666226         -313      0.000    114   0.8961  K*bar0          
         10633425          321    100.000    116   0.4936  K+              
          7113697         -321    100.000    116   0.4936  K-              
          4885706          323      0.000    117   0.8916  K*+             
          2902766         -323      0.000    117   0.8916  K*-             
          3103391          331      0.000    119   0.9578  eta'            
          1188277          333      0.000    120   1.0194  phi             
                2          421    100.000    125   1.8645  D0              
             1082         -421    100.000    125   1.8645  Dbar0           
               91          441      0.000    131   2.9798  eta_c           
             3090          443      0.000    132   3.0969  J/psi           
             6064         1114      0.000    151   1.2340  Delta-          
             7142        -1114      0.000    151   1.2340  Deltabar+       
         53465281         2101      0.000    152   0.5793  ud_0            
         17841476         2103      0.000    153   0.7713  ud_1            
         28241916         2112    100.000    154   0.9396  n0              
           219729        -2112    100.000    154   0.9396  nbar0           
          5566033         2114      0.000    155   1.2330  Delta0          
             8520        -2114      0.000    155   1.2330  Deltabar0       
         35368292         2203      0.000    156   0.7713  uu_1            
         65756047         2212    100.000    157   0.9383  p+              
           235703        -2212    100.000    157   0.9383  pbar-           
         11640213         2214      0.000    158   1.2320  Delta+          
             8856        -2214      0.000    158   1.2320  Deltabar-       
         15943690         2224      0.000    159   1.2310  Delta++         
             7468        -2224      0.000    159   1.2310  Deltabar--      
            59060         3112    100.000    162   1.1974  Sigma-          
            21177        -3112    100.000    162   1.1974  Sigmabar+       
              709         3114      0.000    163   1.3872  Sigma*-         
             1016        -3114      0.000    163   1.3872  Sigma*bar+      
          5024734         3122    100.000    164   1.1157  Lambda0         
            34864        -3122    100.000    164   1.1157  Lambdabar0      
           519797         3212    100.000    167   1.1925  Sigma0          
            26716        -3212    100.000    167   1.1925  Sigmabar0       
           682105         3214      0.000    168   1.3837  Sigma*0         
             1203        -3214      0.000    168   1.3837  Sigma*bar0      
           962052         3222    100.000    169   1.1894  Sigma+          
            23139        -3222    100.000    169   1.1894  Sigmabar-       
          1342402         3224      0.000    170   1.3828  Sigma*+         
             1051        -3224      0.000    170   1.3828  Sigma*bar-      
              683         3312    100.000    172   1.3213  Xi-             
             2371        -3312    100.000    172   1.3213  Xibar+          
               52         3314      0.000    173   1.5350  Xi*-            
              114        -3314      0.000    173   1.5350  Xi*bar+         
              629         3322    100.000    174   1.3149  Xi0             
             2395        -3322    100.000    174   1.3149  Xibar0          
               73         3324      0.000    175   1.5318  Xi*0            
              107        -3324      0.000    175   1.5318  Xi*bar0         
             1186         4122    100.000    181   2.2849  Lambda_c+       
               27         4212      0.000    185   2.4535  Sigma_c+        
               57         4214      0.000    186   2.5000  Sigma*_c+       
               59         4222      0.000    187   2.4529  Sigma_c++       
              109         4224      0.000    188   2.5000  Sigma*_c++      
#+end_example

** Low energy reactions
Below 3 GeV 10 dominant exclusive processes are simulated. The  
energy dependences of the cross section and the kinematical parameterizations
are taken from data. For the single pion production differential cross sections, 
the SAID code from I.Strakovski is used. At the end of a job /BGGEN/
prints out the statistics of the simulated reactions:
#+begin_example
 ====================================================================================================
        1000000 events initialy simulated in the full energy range
         997430 events successfully simulated
         997430 events selected
              0 events written out to HDDM
         997430 events written out to HBOOK NTuple
         195.47 reference interaction rate, kHz
  process                      events   fraction   range
 ----------------------------------------------------------------------------------------------------
      0  PYTHIA                  5723     0.6 %   3.00<E< 3.10 GeV 
 ----------------------------------------------------------------------------------------------------
      1  p pi0                 278024    27.9 %   0.15<E< 3.00 GeV 
      2  n pi+                 368700    37.0 %                    
      3  p pi+ pi-              41772     4.2 %                    
      4  p rho0                 31305     3.1 %                    
      5  Delta++ pi-            86473     8.7 %                    
      6  p pi0 pi0              21473     2.2 %                    
      7  n pi+ pi0             101701    10.2 %                    
      8  p eta                   7425     0.7 %                    
      9  p pi+ pi- pi0          40720     4.1 %                    
     10  n pi+ pi+ pi-          14114     1.4 %                    
 ----------------------------------------------------------------------------------------------------
#+end_example

* Debugging tools

**  Printout
*** Event printout
#+begin_example  
NPRIEV  100
#+end_example
the final event record for the first 100 events will be printed. This is an example of
events form /PYTHIA/:
#+begin_example 
 ================================================================================
 Event      2  Process=   0   PYTHIA                          
           ID        KF                       mass      Px      Py      Pz      name
 beam       1        22                     0.0000      0.000   0.000   9.641   gamma           
 target    14      2212                     0.9383      0.000   0.000   0.000   proton          
 --------------------------------------------------------------------------------
   #    ID    KS     KF   orig  decays        mass      Px      Py      Pz      name
   1     0    12     -2      0   5   5      0.3300      0.152  -0.109   1.003   ubar            
   2     0    11      2      0   5   5      0.3300      0.264   0.078   0.760   u               
   3     0    12      2      0   7   7      0.3300     -0.152   0.109   7.977   u               
   4     0    11   2101      0   8   8      0.5793     -0.264  -0.078  -0.098   ud_0            
   5     0    11     91      1   6   6      0.7088      0.416  -0.031   1.763   cluster         
   6     0    11    113      5   9  10      0.7785      0.409  -0.031   1.891   rho0            
   7     0    12      2      3  11  11      0.3246     -0.150   0.107   7.847   u               
   8     0    11   2101      4  11  11      0.5699     -0.259  -0.077  -0.096   ud_0            
   9     9     1   -211      6   0   0      0.1396      0.242  -0.378   1.032   pi-             
  10     8     1    211      6   0   0      0.1396      0.167   0.347   0.859   pi+             
  11     0    11     92      7  12  14      3.4510     -0.409   0.031   7.750   string          
  12     0    11    113     11  15  16      0.6630      0.279   0.048   0.558   rho0            
  13    17     1    221     11   0   0      0.5475     -0.120   0.085   5.695   eta             
  14    14     1   2212     11   0   0      0.9383     -0.568  -0.102   1.497   proton          
  15     9     1   -211     12   0   0      0.1396      0.089  -0.192  -0.008   pi-             
  16     8     1    211     12   0   0      0.1396      0.190   0.240   0.566   pi+             
#+end_example
here:
+ /ID=/IDG/ - /GEANT3/ particle ID
+ /KF/ - universal particle code (/PYTHIA/, PDG...)
+ /KS/ - /PYTHIA/ particle final status: =1 - a real final particle, >9 - a particle
          fragmented, decayed etc,
          =11 - decayed particle.
         Onlu the particles with /KS=1/ are transferred for tracking in /GEANT/.
+ /orig/ - the mother particle number in this list
+ /decays/ - the 1-st and the last numbers of the daughter particles in the list
             (the numbering is sequential)

Example of locally simulated events (not by /PYTHIA/):  
#+begin_example
 ================================================================================
 Event     10  Process=  -1   Exclusive production J/psi+proton               
           ID        KF                       mass      Px      Py      Pz      name
 beam       1        22                     0.0000      0.000   0.000  11.303   gamma           
 target    14      2212                     0.9383      0.000   0.000   0.000   proton          
 --------------------------------------------------------------------------------
   #    ID    KS     KF   orig  decays        mass      Px      Py      Pz      name
   1     0    10    443      0   3   4      3.0969      0.612  -0.439   9.860   J/psi           
   2    14     1   2212      0   0   0      0.9383     -0.612   0.439   1.443   proton          
   3     2     1    -11      1   0   0      0.0005      0.717   0.090   9.792   e+              
   4     3     1     11      1   0   0      0.0005     -0.105  -0.529   0.068   e-               
#+end_example 


  
