
import os,sbms

Import('*')

subdirs = ['genr8', 'genr8_2_hddm', 'HDGeant', 'mcsmear', 'bggen', 'gen_2k', 'gen_2pi', 'gen_2pi_amp', 'gen_2pi_primakoff','gen_3pi', 'gen_pi0', 'gen_omega_3pi', 'gen_omega_radiative' , 'nullgen', 'gen_amp', 'BGRate_calc', 'genEtaRegge', 'gen_ee', 'gen_ee_hb', 'genScalarRegge', 'gen_compton', 'gen_omegapi', 'gen_compton_simple', 'gen_primex_eta_he4', 'gen_2pi0_primakoff']


# only build if	    EvtGen is installed
EVTGEN_HOME = os.getenv('EVTGENDIR')
if EVTGEN_HOME!=None:
   subdirs += ['decay_evtgen','gen_schannel']

sbms.OptionallyBuild(env, ['genphoton', 'genpi', 'gen_2mu', 'stdhep_translators', 'bggen_jpsi'])

SConscript(dirs=subdirs, exports='env osname', duplicate=0)
