
import os
import sbms

# get env object and clone it
Import('*')

# Verify EVTGENDIR environment variable is set
if os.getenv('EVTGENDIR', 'nada')!='nada':
	
	env = env.Clone()

	sbms.AddEvtGen(env)
	sbms.AddROOT(env)
	sbms.library(env)


