
import os
import sbms

# get env object and clone it
Import('*')

# Verify AMPTOOLS environment variable is set
if os.getenv('CERN', 'nada')!='nada':
   
   env = env.Clone()
   
   UTILITIES_LIBS = "UTILITIES"
   env.AppendUnique(LIBS = UTILITIES_LIBS.split())

   sbms.AddHDDM(env)   
   sbms.AddROOT(env)
   sbms.AddAmpTools(env)
   sbms.AddCERNLIB(env)
   sbms.AddUtilities(env)
 
   sbms.executable(env)

