
import os
import sbms

# get env object and clone it
Import('*')

if os.getenv('AMPTOOLS', 'nada')!='nada':

    env = env.Clone()

    sbms.AddROOT(env)
    sbms.AddAmpTools(env)
    sbms.AddCCDB(env)
    sbms.library(env)
