
import os
import sbms

# get env object and clone it
Import('*')


# Verify CERN environment variable is set
if os.getenv('CERN', 'nada')=='nada':
	if env.Dir('.').srcnode().abspath.startswith(env.GetLaunchDir()):
		print('============================================================')
		print('CERN environment variable not set. Skipping build of bggen')
		print('============================================================')

else:

	env = env.Clone()
	
	# Turn off warnings for bggen since Pythia has too many
	env['FORTRANFLAGS'].remove('-Wall')

	sbms.AddCERNLIB(env)

# Verify AMPTOOLS environment variable is set
if os.getenv('AMPTOOLS', 'nada')!='nada' and os.getenv('CERN', 'nada')!='nada':

   env = env.Clone()

   AMPTOOLS_LIBS = "AMPTOOLS_AMPS AMPTOOLS_DATAIO AMPTOOLS_MCGEN UTILITIES"
   env.AppendUnique(LIBS = AMPTOOLS_LIBS.split())
     
   sbms.AddROOT(env)
   sbms.AddUtilities(env)
   sbms.AddCERNLIB(env)
   
   sbms.executable(env, 'run_sd_compton')	


