

import sbms

# get env object and clone it
Import('*')
env = env.Clone()
# Turn off warnings for bggen since Pythia has too many
fflags = env['FORTRANFLAGS'].remove('-Wall')
env.Replace(FORTRANFLAGS=fflags)
env.PrependUnique(FORTRANFLAGS = ['-ffixed-line-length-80'])
env.PrependUnique(FORTRANFLAGS = ['-std=legacy'])
env.PrependUnique(FORTRANFLAGS = ['-fbounds-check'])
print('DEBUG: call executable method')
sbms.executables(env)


