
import sbms

Import('*')

subdirs = ['etapi_delta_plotter', 'plot_etapi_delta','fit', 'twopi_plotter', 'twopi_plotter_amp', 'twopi_plotter_mom', 'twopi_plotter_primakoff', 'split_mass', 'split_t', 'threepi_plotter_schilling', 'omega_radiative_plotter', 'project_moments']

SConscript(dirs=subdirs, exports='env osname', duplicate=0)

