/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 

// Your description goes here... 

#include "Riostream.h" 

#include "RooAbsReal.h" 
#include "RooAbsCategory.h" 
#include "BreitWignerRooFit.h"
#include <math.h> 
#include "TMath.h" 
#include "complex.h"

using std::complex;
using std::norm;
using std::arg;

 BreitWignerRooFit::BreitWignerRooFit(const char *name, const char *title, 
		      RooAbsReal& _x,
		      RooAbsReal& _mass1,
		      RooAbsReal& _width1,
		      RooAbsReal& _spin1,
		      RooAbsReal& _mass2,
		      RooAbsReal& _width2,
		      RooAbsReal& _spin2,
		      RooAbsReal& _scale,
		      RooAbsReal& _Phi,
		      RooAbsReal& _rInt,
		      RooAbsReal& _massA,
		      RooAbsReal& _massB) :
   RooAbsPdf(name,title), 
   x("x","x",this,_x),
   mass1("mass1","mass1",this,_mass1),
   width1("width1","width1",this,_width1),
   spin1("spin1","spin1",this,_spin1),
   mass2("mass2","mass2",this,_mass2),
   width2("width2","width2",this,_width2),
   spin2("spin2","spin2",this,_spin2),
   scale("scale","scale",this,_scale),
   Phi("Phi","Phi",this,_Phi),
   rInt("rInt","rInt",this,_rInt),
   massA("massA","massA",this,_massA),
   massB("massB","massB",this,_massB)
 { 
 } 


 BreitWignerRooFit::BreitWignerRooFit(const BreitWignerRooFit& other, const char* name) :  
   RooAbsPdf(other,name), 
   x("x",this,other.x),
   mass1("mass1",this,other.mass1),
   width1("width1",this,other.width1),
   spin1("spin1",this,other.spin1),
   mass2("mass2",this,other.mass2),
   width2("width2",this,other.width2),
   spin2("spin2",this,other.spin2),
   scale("scale",this,other.scale),
   Phi("Phi",this,other.Phi),
   rInt("rInt",this,other.rInt),
   massA("massA",this,other.massA),
   massB("massB",this,other.massB)
 { 
 } 



 Double_t BreitWignerRooFit::evaluate() const 
 { 
   // ENTER EXPRESSION IN TERMS OF VARIABLE ARGUMENTS HERE 

  // assert positive breakup momenta     
  Double_t q0_1 = fabs( breakupMomentum(mass1, massA, massB) );
  Double_t q0_2 = fabs( breakupMomentum(mass2, massA, massB) );
  Double_t q  = fabs( breakupMomentum(x,    massA, massB) );
  
  Double_t F0_1 = barrierFactor(q0_1, spin1);
  Double_t F_1  = barrierFactor(q,  spin1);
  Double_t F0_2 = barrierFactor(q0_2, spin2);
  Double_t F_2  = barrierFactor(q,  spin2);

  Double_t calc_width_1 = width1*(mass1/x)*(q/q0_1)*((F_1*F_1)/(F0_1*F0_1));
  Double_t calc_width_2 = width2*(mass2/x)*(q/q0_2)*((F_2*F_2)/(F0_2*F0_2));
  
  // this first factor just gets normalization right for BW's that have
  // no additional s-dependence from orbital L
  // complex<Double_t> bwtop_1( sqrt( mass1*width1 / TMath::Pi() ), 0.0 );
  complex<Double_t> bwtop_1( sqrt( x*calc_width_1 / TMath::Pi() ), 0.0 );
  complex<Double_t> bwbottom_1( ( mass1*mass1 - x*x ) ,
                               -1.0 * ( mass1 * calc_width_1 ) );

  //complex<Double_t> bwtop_2( sqrt( mass2*width2 / TMath::Pi() ), 0.0 );
  complex<Double_t> bwtop_2( sqrt( x*calc_width_2 / TMath::Pi() ), 0.0 );
  complex<Double_t> bwbottom_2( ( mass2*mass2 - x*x ) ,
                               -1.0 * ( mass2 * calc_width_2 ) );

  complex<Double_t> Phase( cos(Phi), sin(Phi));
  Double_t relativeScale = scale;
  Double_t relativeInterference = rInt;
  //return( norm( sqrt(1-relativeScale)*F_1 * bwtop_1 / bwbottom_1 + sqrt(relativeScale)*Phase * F_2 * bwtop_2 / bwbottom_2 ) );

  Double_t term1 = norm( sqrt(1-relativeScale)*F_1 * bwtop_1 / bwbottom_1 );
  Double_t term2 = norm( sqrt(relativeScale)*Phase * F_2 * bwtop_2 / bwbottom_2 );
  Double_t term3 = 2*sqrt(term1)*sqrt(term2)*relativeInterference*
                   cos(arg(bwtop_1 / bwbottom_1)-arg(bwtop_2 / bwbottom_2)-Phi);
  return(  term1 + term2 + term3);

  // double regge next order
 } 


Double_t BreitWignerRooFit::breakupMomentum(double mass0, double mass1, double mass2) const
{
  double q;
  //mass 1 and mass 2 are the daughters of mass 0
	// fabs -- correct?  consistent w/ previous E852 code
        q = sqrt( fabs(   mass0*mass0*mass0*mass0 + 
			  mass1*mass1*mass1*mass1 +
			  mass2*mass2*mass2*mass2 -
			  2.0*mass0*mass0*mass1*mass1 -
			  2.0*mass0*mass0*mass2*mass2 -
			  2.0*mass1*mass1*mass2*mass2  ) ) / (2.0 * mass0);

        return q;
	
}

Double_t BreitWignerRooFit::barrierFactor( double q, int spinP ) const
{  

  double barrier = 1;
  double z;

  z = ( (q*q) / (0.1973*0.1973) );

  switch (spinP){

  case 0:
    barrier = 1.0;
    break;

  case 1:
    barrier = sqrt( (2.0*z) /
		    (z + 1.0) );
    break;
        
  case 2:
    barrier = sqrt( (13.0*z*z) /
		    ((z-3.0)*(z-3.0) + 9.0*z) );
    break;
  }

  return barrier;

}
