/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef BREITWIGNERROOFIT
#define BREITWIGNERROOFIT

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class BreitWignerRooFit : public RooAbsPdf {
public:
  BreitWignerRooFit() {} ; 
  BreitWignerRooFit(const char *name, const char *title,
	    RooAbsReal& _x,
 	    RooAbsReal& _mass1,
	    RooAbsReal& _width1,
	    RooAbsReal& _spin1,
	    RooAbsReal& _mass2,
	    RooAbsReal& _width2,
	    RooAbsReal& _spin2,
	    RooAbsReal& _scale,
	    RooAbsReal& _Phi,
	    RooAbsReal& _rInt, 
	    RooAbsReal& _massA,
	    RooAbsReal& _massB);
  BreitWignerRooFit(const BreitWignerRooFit& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new BreitWignerRooFit(*this,newname); }
  inline virtual ~BreitWignerRooFit() { }

protected:

  RooRealProxy x ;
  RooRealProxy mass1 ;
  RooRealProxy width1 ;
  RooRealProxy spin1 ;
  RooRealProxy mass2 ;
  RooRealProxy width2 ;
  RooRealProxy spin2 ;
  RooRealProxy scale ;
  RooRealProxy Phi ;
  RooRealProxy rInt ; //relative interference
  RooRealProxy massA ;
  RooRealProxy massB ;
  
  Double_t evaluate() const ;

private:

  Double_t breakupMomentum(double mass0, double mass1, double mass2) const;
  Double_t barrierFactor( double q, int spinP ) const;

};
 
#endif
