
import os
import sbms

# get env object and clone it
Import('*')

# Verify AMPTOOLS environment variable is set
if os.getenv('AMPTOOLS', 'nada')!='nada':
	
	env = env.Clone()

	UTILITIES_LIBS = "UTILITIES"
	env.AppendUnique(LIBS = UTILITIES_LIBS.split())

	sbms.AddUtilities(env)
	sbms.AddAmpTools(env)
	sbms.AddROOT(env)
	sbms.library(env)


